### Introduction to TensorFlow

In [4]:
# Import tensorflow and check the version
import tensorflow as tf
print(tf.__version__)

2.12.0


### Constant tensor

In [6]:
# Create tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [8]:
# Create a vector
vector = tf.constant([20,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 20])>

In [9]:
# Check the dimension of the vector
vector.ndim

1

In [10]:
# Create a matrix and check the dimension
matrix = tf.constant([[1,2], [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
# Check the dimension of the matrixf
matrix.ndim

2

In [12]:
# 3 X 3 matrix's dimension
new_matrix = tf.constant([[[1,2,3], [2,3,4,], [3,4,5]]])
new_matrix.ndim

3

In [14]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]], [[1,2,3], [1,2,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])>

In [15]:
tensor.ndim

3

#### So far, we have created:
- scalar
- vector
- matrix
- tensor (n-dimensional)

### variable tensor

In [16]:
variable_tensor = tf.Variable([10,90])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 90])>

In [17]:
# Change the item of the variable
variable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 90])>

In [18]:
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 90])>

In [19]:
# Try to change the item of the constant
constant_tensor = tf.constant([10,50])

In [21]:
constant_tensor[0].assign(60)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [22]:
# we can not assign the value as given below
# variable_tensor[0]= 90

### Creating random tensors
- Random tensors are tensors of some arbitrary size which contain random numbers

In [25]:
# create two random tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [26]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [27]:
# this line of code check the equality of the tensors
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Suffle the order of elements in a tensor

In [28]:
# Shuffle a tensor 
before_suffle = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

In [29]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(before_suffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [30]:
# set the seed 
tf.random.set_seed(42)
tf.random.shuffle(before_suffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

##### If set_seed(42) is not set then the value after shuffle will be changed