### Introduction to TensorFlow

In [4]:
# Import tensorflow and check the version
import tensorflow as tf
print(tf.__version__)

2.12.0


In [6]:
# Create tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [8]:
# Create a vector
vector = tf.constant([20,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 20])>

In [9]:
# Check the dimension of the vector
vector.ndim

1

In [10]:
# Create a matrix and check the dimension
matrix = tf.constant([[1,2], [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
# Check the dimension of the matrixf
matrix.ndim

2

In [12]:
# 3 X 3 matrix's dimension
new_matrix = tf.constant([[[1,2,3], [2,3,4,], [3,4,5]]])
new_matrix.ndim

3

In [14]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]], [[1,2,3], [1,2,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])>

In [15]:
tensor.ndim

3

#### So far, we have created:
- scalar
- vector
- matrix
- tensor (n-dimensional)